In [5]:
%matplotlib inline 
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import matplotlib.pyplot as plt
import numpy as np
import requests
import json
import time
import geoplot as gplt
import geoplot.crs as gcrs
# Dependencies
from citipy import citipy
api_key = "AIzaSyBko3hF5Q0Rs7Zy40NeQPh-zP5Mpt4Lm10"

In [6]:
wine_data_to_load = "/Users/kurtshiple/Desktop/Project1/projectcsvs/wine_data.csv"

wine_data = pd.read_csv(wine_data_to_load)

wine_data.head(10)

,country,points,price,title,variety,winery
0,Portugal,87,15.0,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
1,US,87,14.0,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
2,US,87,13.0,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
3,US,87,65.0,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
4,Spain,87,15.0,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
5,Italy,87,16.0,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
6,France,87,24.0,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
7,Germany,87,12.0,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel
8,France,87,27.0,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
9,US,87,19.0,Kirkland Signature 2011 Mountain Cuvée Caberne...,Cabernet Sauvignon,Kirkland Signature

In [7]:
import geoplot as gplt
import geoplot.crs as gcrs
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

In [8]:
world["wine_score_mean"] = " "
world.head()

,pop_est,continent,name,iso_a3,gdp_md_est,geometry,wine_score_mean
0,28400000.0,Asia,Afghanistan,AFG,22270.0,"POLYGON ((61.21081709172574 35.65007233330923,...",
1,12799293.0,Africa,Angola,AGO,110300.0,(POLYGON ((16.32652835456705 -5.87747039146621...,
2,3639453.0,Europe,Albania,ALB,21810.0,"POLYGON ((20.59024743010491 41.85540416113361,...",
3,4798491.0,Asia,United Arab Emirates,ARE,184300.0,"POLYGON ((51.57951867046327 24.24549713795111,...",
4,40913584.0,South America,Argentina,ARG,573900.0,(POLYGON ((-65.50000000000003 -55.199999999999...,

In [9]:
countrymean = pd.DataFrame(wine_data.groupby("country").points.mean())
countrymeanprice = pd.DataFrame(wine_data.groupby("country").price.mean())
countryvariety = pd.DataFrame(wine_data.groupby("country").variety.count())

In [38]:
countrymeandict = countrymean.to_dict('index')

In [39]:
countrymeanpricedict = countrymeanprice.to_dict('index')

In [40]:
countryvarietydict = countryvariety.to_dict('index')

In [13]:
#AVERAGE SCORE BY COUNTRY
ticker = 0
scorelist = []
for name in world["name"]:
    if name in countrymean.index:
        scorelist.append(countrymeandict[f"{name}"]['points'])
        ticker = ticker +1
    
    else:
        scorelist.append(0)
        
print(f"{ticker} out of 42")

38 out of 42

In [17]:
#AVERAGE PRICE BY COUNTRY
ticker = 0
pricelist = []
for name in world["name"]:
    if name in countrymeanprice.index:
        pricelist.append(countrymeanpricedict[f"{name}"]['price'])
        ticker = ticker +1
    
    else:
        pricelist.append(0)
        
print(f"{ticker} out of 42")

38 out of 42

In [19]:
#FINDING OUR MISSING COUNTRIES
ticker = 0
foundnamelist = []
for name in world["name"]:
    if name in countrymeanprice.index:
        foundnamelist.append(name)
        ticker = ticker +1
    
    else:
        pass
missinglist = []
for country in countrymeanprice.index:
    if country not in foundnamelist:
        missinglist.append(country)
    else:
        pass
print(f"Missing:{missinglist}")

Missing:['Bosnia and Herzegovina', 'Czech Republic', 'England', 'US']

In [21]:
#AVERAGE PRICE BY COUNTRY
ticker = 0
pricelist = []
for name in world["name"]:
    if name in countrymeanprice.index:
        pricelist.append(countrymeanpricedict[f"{name}"]['price'])
        ticker = ticker +1
    
    else:
        pricelist.append(0)
        
print(f"{ticker} out of 42")

38 out of 42

In [22]:
#WINE VALUE BY COUNTRY
ticker = 0
valuelist = []
for i,j in zip(scorelist,pricelist):
    if j != 0:
        valuelist.append(i/j)
        ticker+=1
    else:
        valuelist.append(0)
        
print(f"{ticker} out of 42")

38 out of 42

In [23]:
#WINE VARIETY BY COUNTRY
ticker = 0
varietylist = []
for name in world["name"]:
    if name in countryvariety.index:
        varietylist.append(countryvarietydict[f"{name}"]['variety'])
        ticker = ticker +1
    
    else:
        varietylist.append(0)
        
print(f"{ticker} out of 42")

38 out of 42

In [24]:
#WINE VARIETY PER CAPITA BY COUNTRY
ticker = 0
winevarietypercapitalist = []
for i,j in zip(list(world["pop_est"]),varietylist):
    if j != 0:
        winevarietypercapitalist.append(j/i)
        ticker+=1
    else:
        winevarietypercapitalist.append(0)
        
print(f"{ticker} out of 42")

38 out of 42

In [26]:
world["wine_score_mean"] = scorelist


world["wine_price_mean"] = pricelist



world["value_list"] = valuelist



world["wine_variety"] = varietylist


world["wine_variety_per_capita"] = winevarietypercapitalist

In [27]:
#filling in missing data
missingindexlist = [18,40,57,168]

for i,j in zip(missingindexlist,missinglist):
    world.iloc[i,6] = countrymeandict[f"{j}"]["points"]
    print(countrymeandict[f"{j}"]["points"])
    world.iloc[i,7] = countrymeanpricedict[f"{j}"]["price"]
    world.iloc[i,8] = countrymeandict[f"{j}"]["points"]/countrymeanpricedict[f"{j}"]["price"]
    world.iloc[i,9] = countryvarietydict[f"{j}"]["variety"]
    world.iloc[i,10] = countryvarietydict[f"{j}"]["variety"]/world.iloc[i,0]

86.5
87.25
91.55072463768116
88.56638717405326

In [28]:
world.head(50)

,pop_est,continent,name,iso_a3,gdp_md_est,geometry,wine_score_mean,wine_price_mean,value_list,wine_variety,wine_variety_per_capita
0,2.840000e+07,Asia,Afghanistan,AFG,22270.0,"POLYGON ((61.21081709172574 35.65007233330923,...",0.000000,0.000000,0.000000,0,0.000000e+00
1,1.279929e+07,Africa,Angola,AGO,110300.0,(POLYGON ((16.32652835456705 -5.87747039146621...,0.000000,0.000000,0.000000,0,0.000000e+00
2,3.639453e+06,Europe,Albania,ALB,21810.0,"POLYGON ((20.59024743010491 41.85540416113361,...",0.000000,0.000000,0.000000,0,0.000000e+00
3,4.798491e+06,Asia,United Arab Emirates,ARE,184300.0,"POLYGON ((51.57951867046327 24.24549713795111,...",0.000000,0.000000,0.000000,0,0.000000e+00
4,4.091358e+07,South America,Argentina,ARG,573900.0,(POLYGON ((-65.50000000000003 -55.199999999999...,86.710330,24.510117,3.537736,3756,9.180325e-05
5,2.967004e+06,Asia,Armenia,ARM,18770.0,"POLYGON ((43.58274580259273 41.09214325618257,...",87.500000,14.500000,6.034483,2,6.740807e-07
6,3.802000e+03,Antarctica,Antarctica,ATA,760.4,(POLYGON ((-59.57209469261153 -80.040178725096...,0.000000,0.000000,0.000000,0,0.000000e+00
7,1.400000e+02,Seven seas (open ocean),Fr. S. Antarctic Lands,ATF,16.0,"POLYGON ((68.935 -48.62500000000001, 69.58 -48...",0.000000,0.000000,0.000000,0,0.000000e+00
8,2.126264e+07,Oceania,Australia,AUS,800200.0,(POLYGON ((145.3979781434948 -40.7925485166058...,88.595466,35.437663,2.500037,2294,1.078888e-04
9,8.210281e+06,Europe,Austria,AUT,329500.0,"POLYGON ((16.97966678230404 48.12349701597631,...",90.190782,30.762772,2.931816,2799,3.409140e-04
10,8.238672e+06,Asia,Azerbaijan,AZE,77610.0,"(POLYGON ((45.0019873390568 39.7400035670496, ...",0.000000,0.000000,0.000000,0,0.000000e+00
11,8.988091e+06,Africa,Burundi,BDI,3102.0,POLYGON ((29.33999759290035 -4.499983412294092...,0.000000,0.000000,0.000000,0,0.000000e+00
12,1.041434e+07,Europe,Belgium,BEL,389300.0,"POLYGON ((3.314971144228537 51.34578095153609,...",0.000000,0.000000,0.000000,0,0.000000e+00
13,8.791832e+06,Africa,Benin,BEN,12830.0,"POLYGON ((2.691701694356254 6.258817246928629,...",0.000000,0.000000,0.000000,0,0.000000e+00
14,1.574623e+07,Africa,Burkina Faso,BFA,17820.0,POLYGON ((-2.827496303712707 9.642460842319778...,0.000000,0.000000,0.000000,0,0.000000e+00
15,1.560509e+08,Asia,Bangladesh,BGD,224000.0,"POLYGON ((92.67272098182556 22.04123891854125,...",0.000000,0.000000,0.000000,0,0.000000e+00
16,7.204687e+06,Europe,Bulgaria,BGR,93750.0,"POLYGON ((22.65714969248299 44.23492300066128,...",87.936170,14.645390,6.004358,141,1.957059e-05
17,3.091560e+05,North America,Bahamas,BHS,9093.0,(POLYGON ((-77.53465999999997 23.7597499999999...,0.000000,0.000000,0.000000,0,0.000000e+00
18,4.613414e+06,Europe,Bosnia and Herz.,BIH,29700.0,"POLYGON ((19.00548628101012 44.86023366960916,...",86.500000,12.500000,6.920000,2,4.335184e-07
19,9.648533e+06,Europe,Belarus,BLR,114100.0,"POLYGON ((23.48412763844985 53.91249766704114,...",0.000000,0.000000,0.000000,0,0.000000e+00
20,3.078990e+05,North America,Belize,BLZ,2536.0,POLYGON ((-89.14308041050332 17.80831899664932...,0.000000,0.000000,0.000000,0,0.000000e+00
21,9.775246e+06,South America,Bolivia,BOL,43270.0,POLYGON ((-62.84646847192156 -22.0349854468694...,0.000000,0.000000,0.000000,0,0.000000e+00
22,1.987393e+08,South America,Brazil,BRA,1993000.0,POLYGON ((-57.62513342958296 -30.2162948544542...,84.659574,23.765957,3.562220,47,2.364908e-07
23,3.881900e+05,Asia,Brunei,BRN,20250.0,"POLYGON ((114.2040165548284 4.525873928236805,...",0.000000,0.000000,0.000000,0,0.000000e+00
24,6.911410e+05,Asia,Bhutan,BTN,3524.0,"POLYGON ((91.69665652869668 27.77174184825166,...",0.000000,0.000000,0.000000,0,0.000000e+00
25,1.990876e+06,Africa,Botswana,BWA,27060.0,POLYGON ((25.64916344575016 -18.53602589281899...,0.000000,0.000000,0.000000,0,0.000000e+00
26,4.511488e+06,Africa,Central African Rep.,CAF,3198.0,"POLYGON ((15.27946048346911 7.421924546737969,...",0.000000,0.000000,0.000000,0,0.000000e+00
27,3.348721e+07,North America,Canada,CAN,1300000.0,(POLYGON ((-63.66449999999998 46.5500099999999...,89.377953,35.712598,2.502701,254,7.584986e-06
28,7.604467e+06,Europe,Switzerland,CHE,316700.0,"POLYGON ((9.59422610844635 47.52505809182027, ...",88.571429,85.285714,1.038526,7,9.205116e-07
29,1.660171e+07,South America,Chile,CHL,244500.0,(POLYGON ((-68.63401022758316 -52.636370458874...,86.495130,20.787316,4.160957,4415,2.659365e-04
30,1.338613e+09,Asia,China,CHN,7973000.0,(POLYGON ((110.3391878601516 18.67839508714761...,89.000000,18.000000,4.944444,1,7.470419e-10
31,2.061707e+07,Africa,Côte d'Ivoire,CIV,33850.0,POLYGON ((-2.856125047202397 4.994475816259509...,0.000000,0.000000,0.000000,0,0.000000e+00
32,1.887930e+07,Africa,Cameroon,CMR,42750.0,"POLYGON ((13.07582238124675 2.267097072759015,...",0.000000,0.000000,0.000000,0,0.000000e+00
33,6.869254e+07,Africa,Dem. Rep. Congo,COD,20640.0,"POLYGON ((30.83385989759381 3.509165961110341,...",0.000000,0.000000,0.000000,0,0.000000e+00
34,4.012809e+06,Africa,Congo,COG,15350.0,POLYGON ((12.99551720546518 -4.781103203961884...,0.000000,0.000000,0.000000,0,0.000000e+00
35,4.564402e+07,South America,Colombia,COL,395400.0,POLYGON ((-75.37322323271385 -0.15203175212045...,0.000000,0.000000,0.000000,0,0.000000e+00
36,4.253877e+06,North America,Costa Rica,CRI,48320.0,POLYGON ((-82.96578304719736 8.225027980985985...,0.000000,0.000000,0.000000,0,0.000000e+00
37,1.145165e+07,North America,Cuba,CUB,108200.0,POLYGON ((-82.26815121125706 23.18861074471771...,0.000000,0.000000,0.000000,0,0.000000e+00
38,2.651000e+05,Asia,N. Cyprus,-99,3600.0,"POLYGON ((32.73178022637745 35.14002594658844,...",0.000000,0.000000,0.000000,0,0.000000e+00
39,5.316400e+05,Asia,Cyprus,CYP,22700.0,"POLYGON ((33.97361657078346 35.058506374648, 3...",87.181818,16.272727,5.357542,11,2.069069e-05
40,1.021190e+07,Europe,Czech Rep.,CZE,265200.0,"POLYGON ((16.96028812019458 48.5969823268506, ...",87.250000,24.250000,3.597938,12,1.175099e-06
41,8.232976e+07,Europe,Germany,DEU,2918000.0,"POLYGON ((9.921906365609232 54.98310415304803,...",89.836321,42.257547,2.125924,2120,2.575011e-05
42,5.160550e+05,Africa,Djibouti,DJI,1885.0,"POLYGON ((43.08122602720016 12.69963857670712,...",0.000000,0.000000,0.000000,0,0.000000e+00
43,5.500510e+06,Europe,Denmark,DNK,203600.0,(POLYGON ((12.69000613775563 55.60999095318078...,0.000000,0.000000,0.000000,0,0.000000e+00
44,9.650054e+06,North America,Dominican Rep.,DOM,78000.0,POLYGON ((-71.71236141629296 19.71445587816736...,0.000000,0.000000,0.000000,0,0.000000e+00
45,3.417819e+07,Africa,Algeria,DZA,232900.0,"POLYGON ((11.99950564947161 23.47166840259645,...",0.000000,0.000000,0.000000,0,0.000000e+00
46,1.457310e+07,South America,Ecuador,ECU,107700.0,POLYGON ((-80.30256059438722 -3.40485645916471...,0.000000,0.000000,0.000000,0,0.000000e+00
47,8.308287e+07,Africa,Egypt,EGY,443700.0,"POLYGON ((34.9226 29.50133, 34.64174 29.09942,...",0.000000,0.000000,0.000000,0,0.000000e+00
48,5.647168e+06,Africa,Eritrea,ERI,3945.0,"POLYGON ((42.35156000000012 12.54223000000013,...",0.000000,0.000000,0.000000,0,0.000000e+00
49,4.052500e+07,Europe,Spain,ESP,1403000.0,POLYGON ((-9.034817674180246 41.88057058365968...,87.290735,28.215275,3.093740,6573,1.621962e-04

In [36]:
#This takes the resulting df and exports it to csv
world.to_csv("/Users/kurtshiple/Desktop/Project1/projectcsvs/worldwineinforbycountrygeomap.csv", encoding='utf-8', index=False)